BEGIN;
DELETE FROM "blog_holdongametime_blogtag";
DELETE FROM "auth_user_user_permissions";
DELETE FROM "blog_holdongametime_game";
DELETE FROM "blog_holdongametime_post";
DELETE FROM "django_content_type";
DELETE FROM "django_admin_log";
DELETE FROM "auth_permission";
DELETE FROM "blog_holdongametime_bug";
DELETE FROM "blog_holdongametime_mailinglist";
DELETE FROM "auth_user";
DELETE FROM "auth_group_permissions";
DELETE FROM "django_session";
DELETE FROM "blog_holdongametime_faq";
DELETE FROM "blog_holdongametime_review";
DELETE FROM "auth_user_groups";
UPDATE "sqlite_sequence" SET "seq" = 0 WHERE "name" IN ('blog_holdongametime_blogtag', 'auth_user_user_permissions', 'blog_holdongametime_game', 'blog_holdongametime_post', 'django_content_type', 'django_admin_log', 'auth_permission', 'blog_holdongametime_bug', 'blog_holdongametime_mailinglist', 'auth_user', 'auth_group_permissions', 'django_session', 'blog_holdongametime_faq', 'blog_holdongametime_review', 'auth_user_groups');
COMMIT;
