# Generated by Django 3.1.5 on 2021-01-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_holdongametime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500, unique=True)),
                ('answer', models.TextField(max_length=500, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='steam_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
