# Generated by Django 3.1.5 on 2021-01-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_holdongametime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(),
        ),
    ]
