# Generated by Django 3.1.5 on 2021-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_holdongametime', '0003_game_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Acquired'), (2, 'Started'), (3, 'Completed'), (4, 'Reviewed'), (5, 'Suggested'), (6, 'Published')], default=0),
        ),
    ]
