# Generated by Django 3.1.5 on 2021-01-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_holdongametime', '0004_auto_20210110_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
    ]
