# Generated by Django 3.1.5 on 2021-01-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_holdongametime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('creator', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField()),
                ('steam_link', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Acquired'), (2, 'Started'), (3, 'Completed'), (4, 'Reviewed'), (5, 'Suggested')], default=0)),
            ],
        ),
    ]
